//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FindError
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ATM.
    /// </summary>
    // *** Start programmer edit section *** (ATM CustomAttributes)

    // *** End programmer edit section *** (ATM CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ATME", new string[] {
            "Adress as \'Adress\'",
            "MangedBy as \'Manged by\'",
            "Bank as \'Bank\'",
            "Bank.Name as \'Name\'"}, Hidden=new string[] {
            "Bank.Name"})]
    [MasterViewDefineAttribute("ATME", "Bank", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ATML", new string[] {
            "Adress as \'Adress\'",
            "MangedBy as \'Manged by\'",
            "Bank.Name as \'Name\'"})]
    public class ATM : ICSSoft.STORMNET.DataObject
    {
        
        private string fAdress;
        
        private string fMangedBy;
        
        private IIS.FindError.Bank fBank;
        
        // *** Start programmer edit section *** (ATM CustomMembers)

        // *** End programmer edit section *** (ATM CustomMembers)

        
        /// <summary>
        /// Adress.
        /// </summary>
        // *** Start programmer edit section *** (ATM.Adress CustomAttributes)

        // *** End programmer edit section *** (ATM.Adress CustomAttributes)
        [StrLen(255)]
        public virtual string Adress
        {
            get
            {
                // *** Start programmer edit section *** (ATM.Adress Get start)

                // *** End programmer edit section *** (ATM.Adress Get start)
                string result = this.fAdress;
                // *** Start programmer edit section *** (ATM.Adress Get end)

                // *** End programmer edit section *** (ATM.Adress Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATM.Adress Set start)

                // *** End programmer edit section *** (ATM.Adress Set start)
                this.fAdress = value;
                // *** Start programmer edit section *** (ATM.Adress Set end)

                // *** End programmer edit section *** (ATM.Adress Set end)
            }
        }
        
        /// <summary>
        /// MangedBy.
        /// </summary>
        // *** Start programmer edit section *** (ATM.MangedBy CustomAttributes)

        // *** End programmer edit section *** (ATM.MangedBy CustomAttributes)
        [StrLen(255)]
        public virtual string MangedBy
        {
            get
            {
                // *** Start programmer edit section *** (ATM.MangedBy Get start)

                // *** End programmer edit section *** (ATM.MangedBy Get start)
                string result = this.fMangedBy;
                // *** Start programmer edit section *** (ATM.MangedBy Get end)

                // *** End programmer edit section *** (ATM.MangedBy Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATM.MangedBy Set start)

                // *** End programmer edit section *** (ATM.MangedBy Set start)
                this.fMangedBy = value;
                // *** Start programmer edit section *** (ATM.MangedBy Set end)

                // *** End programmer edit section *** (ATM.MangedBy Set end)
            }
        }
        
        /// <summary>
        /// ATM.
        /// </summary>
        // *** Start programmer edit section *** (ATM.Bank CustomAttributes)

        // *** End programmer edit section *** (ATM.Bank CustomAttributes)
        [NotNull()]
        public virtual IIS.FindError.Bank Bank
        {
            get
            {
                // *** Start programmer edit section *** (ATM.Bank Get start)

                // *** End programmer edit section *** (ATM.Bank Get start)
                IIS.FindError.Bank result = this.fBank;
                // *** Start programmer edit section *** (ATM.Bank Get end)

                // *** End programmer edit section *** (ATM.Bank Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATM.Bank Set start)

                // *** End programmer edit section *** (ATM.Bank Set start)
                this.fBank = value;
                // *** Start programmer edit section *** (ATM.Bank Set end)

                // *** End programmer edit section *** (ATM.Bank Set end)
            }
        }
        
        // *** Start programmer edit section *** (ATM.identifies CustomAttributes)

        // *** End programmer edit section *** (ATM.identifies CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void identifies()
        {
            // *** Start programmer edit section *** (ATM.identifies method implementation)

            return;
            // *** End programmer edit section *** (ATM.identifies method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ATME" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ATME
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ATME", typeof(IIS.FindError.ATM));
                }
            }
            
            /// <summary>
            /// "ATML" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ATML
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ATML", typeof(IIS.FindError.ATM));
                }
            }
        }
    }
}
