//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FindError
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// A t m  transaction.
    /// </summary>
    // *** Start programmer edit section *** (ATMTransaction CustomAttributes)

    // *** End programmer edit section *** (ATMTransaction CustomAttributes)
    [AutoAltered()]
    [Caption("A t m  transaction")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ATMTransactionE", new string[] {
            "TransactionId as \'Transaction id\'",
            "TransactionDate as \'Transaction date\'",
            "Amount as \'Amount\'",
            "Account as \'Account\'",
            "Account.AccountType as \'Account type\'",
            "ATM as \'ATM\'",
            "ATM.Adress as \'Adress\'"}, Hidden=new string[] {
            "Account.AccountType",
            "ATM.Adress"})]
    [MasterViewDefineAttribute("ATMTransactionE", "Account", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "AccountType")]
    [MasterViewDefineAttribute("ATMTransactionE", "ATM", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Adress")]
    [View("ATMTransactionL", new string[] {
            "TransactionId as \'Transaction id\'",
            "TransactionDate as \'Transaction date\'",
            "Amount as \'Amount\'",
            "Account.AccountType as \'Account type\'",
            "ATM.Adress as \'Adress\'"})]
    public class ATMTransaction : ICSSoft.STORMNET.DataObject
    {
        
        private int fTransactionId;
        
        private string fTransactionDate;
        
        private int fAmount;
        
        private IIS.FindError.Account fAccount;
        
        private IIS.FindError.ATM fATM;
        
        // *** Start programmer edit section *** (ATMTransaction CustomMembers)

        // *** End programmer edit section *** (ATMTransaction CustomMembers)

        
        /// <summary>
        /// TransactionId.
        /// </summary>
        // *** Start programmer edit section *** (ATMTransaction.TransactionId CustomAttributes)

        // *** End programmer edit section *** (ATMTransaction.TransactionId CustomAttributes)
        public virtual int TransactionId
        {
            get
            {
                // *** Start programmer edit section *** (ATMTransaction.TransactionId Get start)

                // *** End programmer edit section *** (ATMTransaction.TransactionId Get start)
                int result = this.fTransactionId;
                // *** Start programmer edit section *** (ATMTransaction.TransactionId Get end)

                // *** End programmer edit section *** (ATMTransaction.TransactionId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATMTransaction.TransactionId Set start)

                // *** End programmer edit section *** (ATMTransaction.TransactionId Set start)
                this.fTransactionId = value;
                // *** Start programmer edit section *** (ATMTransaction.TransactionId Set end)

                // *** End programmer edit section *** (ATMTransaction.TransactionId Set end)
            }
        }
        
        /// <summary>
        /// TransactionDate.
        /// </summary>
        // *** Start programmer edit section *** (ATMTransaction.TransactionDate CustomAttributes)

        // *** End programmer edit section *** (ATMTransaction.TransactionDate CustomAttributes)
        [StrLen(255)]
        public virtual string TransactionDate
        {
            get
            {
                // *** Start programmer edit section *** (ATMTransaction.TransactionDate Get start)

                // *** End programmer edit section *** (ATMTransaction.TransactionDate Get start)
                string result = this.fTransactionDate;
                // *** Start programmer edit section *** (ATMTransaction.TransactionDate Get end)

                // *** End programmer edit section *** (ATMTransaction.TransactionDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATMTransaction.TransactionDate Set start)

                // *** End programmer edit section *** (ATMTransaction.TransactionDate Set start)
                this.fTransactionDate = value;
                // *** Start programmer edit section *** (ATMTransaction.TransactionDate Set end)

                // *** End programmer edit section *** (ATMTransaction.TransactionDate Set end)
            }
        }
        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (ATMTransaction.Amount CustomAttributes)

        // *** End programmer edit section *** (ATMTransaction.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (ATMTransaction.Amount Get start)

                // *** End programmer edit section *** (ATMTransaction.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (ATMTransaction.Amount Get end)

                // *** End programmer edit section *** (ATMTransaction.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATMTransaction.Amount Set start)

                // *** End programmer edit section *** (ATMTransaction.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (ATMTransaction.Amount Set end)

                // *** End programmer edit section *** (ATMTransaction.Amount Set end)
            }
        }
        
        /// <summary>
        /// A t m  transaction.
        /// </summary>
        // *** Start programmer edit section *** (ATMTransaction.Account CustomAttributes)

        // *** End programmer edit section *** (ATMTransaction.Account CustomAttributes)
        [NotNull()]
        public virtual IIS.FindError.Account Account
        {
            get
            {
                // *** Start programmer edit section *** (ATMTransaction.Account Get start)

                // *** End programmer edit section *** (ATMTransaction.Account Get start)
                IIS.FindError.Account result = this.fAccount;
                // *** Start programmer edit section *** (ATMTransaction.Account Get end)

                // *** End programmer edit section *** (ATMTransaction.Account Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATMTransaction.Account Set start)

                // *** End programmer edit section *** (ATMTransaction.Account Set start)
                this.fAccount = value;
                // *** Start programmer edit section *** (ATMTransaction.Account Set end)

                // *** End programmer edit section *** (ATMTransaction.Account Set end)
            }
        }
        
        /// <summary>
        /// A t m  transaction.
        /// </summary>
        // *** Start programmer edit section *** (ATMTransaction.ATM CustomAttributes)

        // *** End programmer edit section *** (ATMTransaction.ATM CustomAttributes)
        [NotNull()]
        public virtual IIS.FindError.ATM ATM
        {
            get
            {
                // *** Start programmer edit section *** (ATMTransaction.ATM Get start)

                // *** End programmer edit section *** (ATMTransaction.ATM Get start)
                IIS.FindError.ATM result = this.fATM;
                // *** Start programmer edit section *** (ATMTransaction.ATM Get end)

                // *** End programmer edit section *** (ATMTransaction.ATM Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ATMTransaction.ATM Set start)

                // *** End programmer edit section *** (ATMTransaction.ATM Set start)
                this.fATM = value;
                // *** Start programmer edit section *** (ATMTransaction.ATM Set end)

                // *** End programmer edit section *** (ATMTransaction.ATM Set end)
            }
        }
        
        // *** Start programmer edit section *** (ATMTransaction.printreceipt CustomAttributes)

        // *** End programmer edit section *** (ATMTransaction.printreceipt CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void printreceipt()
        {
            // *** Start programmer edit section *** (ATMTransaction.printreceipt method implementation)

            return;
            // *** End programmer edit section *** (ATMTransaction.printreceipt method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ATMTransactionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ATMTransactionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ATMTransactionE", typeof(IIS.FindError.ATMTransaction));
                }
            }
            
            /// <summary>
            /// "ATMTransactionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ATMTransactionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ATMTransactionL", typeof(IIS.FindError.ATMTransaction));
                }
            }
        }
    }
}
