//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FindError
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bank.
    /// </summary>
    // *** Start programmer edit section *** (Bank CustomAttributes)

    // *** End programmer edit section *** (Bank CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BankE", new string[] {
            "Name as \'Name\'"})]
    [View("BankL", new string[] {
            "Name as \'Name\'"})]
    public class Bank : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Bank CustomMembers)

        // *** End programmer edit section *** (Bank CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Bank.Name CustomAttributes)

        // *** End programmer edit section *** (Bank.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Bank.Name Get start)

                // *** End programmer edit section *** (Bank.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Bank.Name Get end)

                // *** End programmer edit section *** (Bank.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bank.Name Set start)

                // *** End programmer edit section *** (Bank.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Bank.Name Set end)

                // *** End programmer edit section *** (Bank.Name Set end)
            }
        }
        
        // *** Start programmer edit section *** (Bank.manages CustomAttributes)

        // *** End programmer edit section *** (Bank.manages CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void manages()
        {
            // *** Start programmer edit section *** (Bank.manages method implementation)

            return;
            // *** End programmer edit section *** (Bank.manages method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BankE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BankE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BankE", typeof(IIS.FindError.Bank));
                }
            }
            
            /// <summary>
            /// "BankL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BankL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BankL", typeof(IIS.FindError.Bank));
                }
            }
        }
    }
}
